<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AuthenticationContractController.cs" />
    <Compile Remove="Controllers\BannerController.cs" />
    <Compile Remove="Controllers\BCBaoCaoController.cs" />
    <Compile Remove="Controllers\BCBaoCaoDoiTuongController.cs" />
    <Compile Remove="Controllers\BCDotBaoCaoController.cs" />
    <Compile Remove="Controllers\BCFormTemplateController.cs" />
    <Compile Remove="Controllers\BCSubmissionController.cs" />
    <Compile Remove="Controllers\BieuMauController.cs" />
    <Compile Remove="Controllers\CompanyInfoController.cs" />
    <Compile Remove="Controllers\DangKyXemController.cs" />
    <Compile Remove="Controllers\DangKyXemLogController.cs" />
    <Compile Remove="Controllers\DangKyXemNenTangController.cs" />
    <Compile Remove="Controllers\DvcSyncController.cs" />
    <Compile Remove="Controllers\DvcSyncLogController.cs" />
    <Compile Remove="Controllers\EnterprisePlatformItemController.cs" />
    <Compile Remove="Controllers\HistoryChangedAuthencationContractController.cs" />
    <Compile Remove="Controllers\HolidayConfigsController.cs" />
    <Compile Remove="Controllers\HomeBlockController.cs" />
    <Compile Remove="Controllers\MauBaoCaoChiTietController.cs" />
    <Compile Remove="Controllers\MauBaoCaoController.cs" />
    <Compile Remove="Controllers\MauTraLoiController.cs" />
    <Compile Remove="Controllers\NavMenuController.cs" />
    <Compile Remove="Controllers\NenTangViPhamController.cs" />
    <Compile Remove="Controllers\PhanAnhNenTangController.cs" />
    <Compile Remove="Controllers\PlatformManageController.cs" />
    <Compile Remove="Controllers\ProcessingDeadlineConfigController.cs" />
    <Compile Remove="Controllers\RutTienKyQuyController.cs" />
    <Compile Remove="Controllers\TinTucController.cs" />
    <Compile Remove="Controllers\VanBanPhapLuatController.cs" />
    <Compile Remove="Controllers\VuViecPhanAnhController.cs" />
    <Compile Remove="Controllers\VuViecTraoDoiController.cs" />
    <Compile Remove="Controllers\WeeklyConfigController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.4.2" />
    <PackageReference Include="EPPlus" Version="7.5.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.18" />
    <PackageReference Include="NCalcSync" Version="6.4.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.18" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\API\CommonHelper\CommonHelper.csproj" />
    <ProjectReference Include="..\..\API\Hinet.Model\Hinet.Model.csproj" />
    <ProjectReference Include="..\..\API\Hinet.Repository\Hinet.Repository.csproj" />
    <ProjectReference Include="..\..\API\Hinet.Service\Hinet.Service.csproj" />
    <ProjectReference Include="..\..\shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
